# https://blogs.technet.microsoft.com/heyscriptingguy/2011/07/24/create-a-simple-graphical-interface-for-a-powershell-script/

Function BuildCommandLine ($Script,$Source,$Destination,$Sort,$Simple,$Smart,$CSSFile,$Prefix,$Suffix,$Details,$Indent,$Inline,$Keep,$Separate,$Log,$LogName) {
   $CommandLine = "$Script -Source '$Source' -Destination '$Destination' -Sort $Sort -SimpleImageScale $Simple -SmartImageScale $Smart -CSSFileName '$CSSFile'"
   if ($Prefix) {$CommandLine = $CommandLine + " -Prefix"}
   if ($Suffix) {$CommandLine = $CommandLine + " -Suffix"}
   if ($Details) {$CommandLine = $CommandLine + " -Details"}
   if ($Indent) {$CommandLine = $CommandLine + " -Indent"}
   if ($Separate) {$CommandLine = $CommandLine + " -SeparateSnippets"}
   if ($Inline) {$CommandLine = $CommandLine + " -InlineStats"}
   if ($Keep) {$CommandLine = $CommandLine + " -KeepStyles"}
   if ($Log) {$CommandLine = $CommandLine + " -Log '$LogName'"}
   Return $CommandLine
} # Function BuildCommandLine


#Generated Form Function
function GenerateForm {
   ########################################################################
   # Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.8.0
   # Generated On: 7/3/2011 11:35 AM
   # Generated By: sean.kearney
   # 
   # Modified and adapted by EightBitz as a GUI for RWExport-To-HTML.ps1
   # Modified and Adapted On: 1/24/2017 5:00 AM CST
   ########################################################################

   #region Import the Assemblies
   [reflection.assembly]::loadwithpartialname(“System.Windows.Forms”) | Out-Null
   [reflection.assembly]::loadwithpartialname(“System.Drawing”) | Out-Null
   #endregion

   #region Generated Form Objects
   $RWExportForm = New-Object System.Windows.Forms.Form

   $ScriptButton = New-Object System.Windows.Forms.Button
   $ScriptText = New-Object System.Windows.Forms.TextBox

   $SourceButton = New-Object System.Windows.Forms.Button
   $SourceText = New-Object System.Windows.Forms.TextBox

   $DestinationButton = New-Object System.Windows.Forms.Button
   $DestinationText = New-Object System.Windows.Forms.TextBox

   $CSSButton = New-Object System.Windows.Forms.Button
   $CSSText = New-Object System.Windows.Forms.TextBox

   $LogCheck = New-Object System.Windows.Forms.CheckBox
   $LogButton = New-Object System.Windows.Forms.Button
   $LogText = New-Object System.Windows.Forms.TextBox

   $SortLabel = New-Object System.Windows.Forms.Label
   $SortComboBox = New-Object System.Windows.Forms.ComboBox
   
   $SimpleImgLabel = New-Object System.Windows.Forms.Label
   $SimpleImgText = New-Object System.Windows.Forms.TextBox

   $SmartImgLabel = New-Object System.Windows.Forms.Label
   $SmartImgText = New-Object System.Windows.Forms.TextBox

   $PrefixCheck = New-Object System.Windows.Forms.CheckBox
   $PrefixLabel = New-Object System.Windows.Forms.Label

   $SuffixCheck = New-Object System.Windows.Forms.CheckBox
   $SuffixLabel = New-Object System.Windows.Forms.Label

   $DetailsCheck = New-Object System.Windows.Forms.CheckBox
   $DetailsLabel = New-Object System.Windows.Forms.Label
   
   $IndentCheck = New-Object System.Windows.Forms.CheckBox
   $IndentLabel = New-Object System.Windows.Forms.Label
   
   $InlineStatsCheck = New-Object System.Windows.Forms.CheckBox
   $InlineStatsLabel = New-Object System.Windows.Forms.Label
   
   $KeepStylesCheck = New-Object System.Windows.Forms.CheckBox
   $KeepStylesLabel = New-Object System.Windows.Forms.Label

   $SeparateCheck = New-Object System.Windows.Forms.CheckBox
   $SeparateLabel = New-Object System.Windows.Forms.Label

   $CommandLabel = New-Object System.Windows.Forms.Label
   $CommandText = New-Object System.Windows.Forms.TextBox

   $RunButton = New-Object System.Windows.Forms.Button
   $SaveButton = New-Object System.Windows.Forms.Button
   $LoadButton = New-Object System.Windows.Forms.Button

   $InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
   #endregion Generated Form Objects

   #———————————————-
   #Generated Event Script Blocks
   #———————————————-
   #Provide Custom Code for events specified in PrimalForms.

      $handler_ScriptButton_Click={
         $OpenFileDialog = New-Object System.Windows.Forms.OpenFileDialog
         $OpenFileDialog.initialDirectory = ".\"
         $OpenFileDialog.filter = “PowerShell Scripts (*.ps1)| *.ps1”
         # $OpenFileDialog.showhelp = $true
         [void]$OpenFileDialog.ShowDialog()
         $ScriptText.Text = $OpenFileDialog.filename.ToString()
         $SortMethod = $SortComboBox.SelectedIndex + 1
         $CommandLine = BuildCommandLine $ScriptText.Text $SourceText.Text $DestinationText.Text $SortMethod $SimpleImgText.Text $SmartImgText.Text $CSSText.Text $PrefixCheck.Checked $SuffixCheck.Checked $DetailsCheck.checked $IndentCheck.Checked $InlineStatsCheck.Checked $KeepStylesCheck.Checked $SeparateCheck.Checked $LogCheck.Checked $LogText.Text
         $CommandText.Text = $CommandLine   
      } # $handler_ScriptButton_Click

      $handler_TextBox_LostFocus={
         $SortMethod = $SortComboBox.SelectedIndex + 1
         $CommandLine = BuildCommandLine $ScriptText.Text $SourceText.Text $DestinationText.Text $SortMethod $SimpleImgText.Text $SmartImgText.Text $CSSText.Text $PrefixCheck.Checked $SuffixCheck.Checked $DetailsCheck.checked $IndentCheck.Checked $InlineStatsCheck.Checked $KeepStylesCheck.Checked $SeparateCheck.Checked $LogCheck.Checked $LogText.Text
         $CommandText.Text = $CommandLine
      } # $handler_ScriptText_LostFocus

      $handler_SourceButton_Click={
         $OpenFileDialog = New-Object System.Windows.Forms.OpenFileDialog
         $OpenFileDialog.initialDirectory = ".\"
         $OpenFileDialog.filter = “Realm Works Exports (*.RWOutput)| *.RWOutput”
         # $OpenFileDialog.showhelp = $true
         [void]$OpenFileDialog.ShowDialog()
         $SourceText.Text = $OpenFileDialog.filename.ToString()
         $SortMethod = $SortComboBox.SelectedIndex + 1
         $CommandLine = BuildCommandLine $ScriptText.Text $SourceText.Text $DestinationText.Text $SortMethod $SimpleImgText.Text $SmartImgText.Text $CSSText.Text $PrefixCheck.Checked $SuffixCheck.Checked $DetailsCheck.checked $IndentCheck.Checked $InlineStatsCheck.Checked $KeepStylesCheck.Checked $SeparateCheck.Checked $LogCheck.Checked $LogText.Text
         $CommandText.Text = $CommandLine
      } # $handler_SourceButton_Click

      $handler_DestinationButton_Click={
         $SaveFileDialog = New-Object System.Windows.Forms.SaveFileDialog
         $SaveFileDialog.initialDirectory = ".\"
         $SaveFileDialog.filter = “HTML Files (*.html)| *.html”
         # $OpenFileDialog.showhelp = $true
         [void]$SaveFileDialog.ShowDialog()
         $DestinationText.Text = $SaveFileDialog.filename
         $SortMethod = $SortComboBox.SelectedIndex + 1
         $CommandLine = BuildCommandLine $ScriptText.Text $SourceText.Text $DestinationText.Text $SortMethod $SimpleImgText.Text $SmartImgText.Text $CSSText.Text $PrefixCheck.Checked $SuffixCheck.Checked $DetailsCheck.checked $IndentCheck.Checked $InlineStatsCheck.Checked $KeepStylesCheck.Checked $SeparateCheck.Checked $LogCheck.Checked $LogText.Text
         $CommandText.Text = $CommandLine
      } # $handler_DestinationButton_Click

      $handler_CSSButton_Click={
         $SaveFileDialog = New-Object System.Windows.Forms.SaveFileDialog
         $SaveFileDialog.initialDirectory = ".\"
         $SaveFileDialog.filter = “CSS Files (*.css)| *.css”
         # $OpenFileDialog.showhelp = $true
         [void]$SaveFileDialog.ShowDialog()
         $CSSText.Text = $SaveFileDialog.filename
         $SortMethod = $SortComboBox.SelectedIndex + 1
         $CommandLine = BuildCommandLine $ScriptText.Text $SourceText.Text $DestinationText.Text $SortMethod $SimpleImgText.Text $SmartImgText.Text $CSSText.Text $PrefixCheck.Checked $SuffixCheck.Checked $DetailsCheck.checked $IndentCheck.Checked $InlineStatsCheck.Checked $KeepStylesCheck.Checked $SeparateCheck.Checked $LogCheck.Checked $LogText.Text
         $CommandText.Text = $CommandLine
      } # $handler_CSSButton_Click

      $handler_CSSText_LostFocus={
         $SortMethod = $SortComboBox.SelectedIndex + 1
         $CommandLine = BuildCommandLine $ScriptText.Text $SourceText.Text $DestinationText.Text $SortMethod $SimpleImgText.Text $SmartImgText.Text $CSSText.Text $PrefixCheck.Checked $SuffixCheck.Checked $DetailsCheck.checked $IndentCheck.Checked $InlineStatsCheck.Checked $KeepStylesCheck.Checked $SeparateCheck.Checked $LogCheck.Checked $LogText.Text
         $CommandText.Text = $CommandLine
      } # $handler_CSSText_LostFocus

      $handler_LogButton_Click={
         $OpenFileDialog = New-Object System.Windows.Forms.OpenFileDialog
         $OpenFileDialog.initialDirectory = ".\"
         $OpenFileDialog.filter = “All files (*.*)| *.*”
         # $OpenFileDialog.showhelp = $true
         [void]$OpenFileDialog.ShowDialog()
         $LogText.Text = $OpenFileDialog.filename.ToString()
         $SortMethod = $SortComboBox.SelectedIndex + 1
         $CommandLine = BuildCommandLine $ScriptText.Text $SourceText.Text $DestinationText.Text $SortMethod $SimpleImgText.Text $SmartImgText.Text $CSSText.Text $PrefixCheck.Checked $SuffixCheck.Checked $DetailsCheck.checked $IndentCheck.Checked $InlineStatsCheck.Checked $KeepStylesCheck.Checked $SeparateCheck.Checked $LogCheck.Checked $LogText.Text
         $CommandText.Text = $CommandLine
      } # $handler_LogButton_Click

      $SortComboBox_SelectedIndexChanged={
         $SortMethod = $SortComboBox.SelectedIndex + 1
         $CommandLine = BuildCommandLine $ScriptText.Text $SourceText.Text $DestinationText.Text $SortMethod $SimpleImgText.Text $SmartImgText.Text $CSSText.Text $PrefixCheck.Checked $SuffixCheck.Checked $DetailsCheck.checked $IndentCheck.Checked $InlineStatsCheck.Checked $KeepStylesCheck.Checked $SeparateCheck.Checked $LogCheck.Checked $LogText.Text
         $CommandText.Text = $CommandLine
      } # $SortComboBox_SelectedIndexChanged

      $handler_CheckBox_CheckStateChanged={
         $SortMethod = $SortComboBox.SelectedIndex + 1
         $CommandLine = BuildCommandLine $ScriptText.Text $SourceText.Text $DestinationText.Text $SortMethod $SimpleImgText.Text $SmartImgText.Text $CSSText.Text $PrefixCheck.Checked $SuffixCheck.Checked $DetailsCheck.checked $IndentCheck.Checked $InlineStatsCheck.Checked $KeepStylesCheck.Checked $SeparateCheck.Checked $LogCheck.Checked $LogText.Text
         $CommandText.Text = $CommandLine
      } # $handler_CheckBox_CheckStateChanged

      $handler_LogCheck_CheckStateChanged={
         if ($LogCheck.Checked) {
            $LogButton.Enabled = $true
            $LogText.Enabled = $true
         } else {
            $LogButton.Enabled = $false
            $LogText.Enabled = $false
         } # if ($LogCheck.Checked)

         $SortMethod = $SortComboBox.SelectedIndex + 1
         $CommandLine = BuildCommandLine $ScriptText.Text $SourceText.Text $DestinationText.Text $SortMethod $SimpleImgText.Text $SmartImgText.Text $CSSText.Text $PrefixCheck.Checked $SuffixCheck.Checked $DetailsCheck.checked $IndentCheck.Checked $InlineStatsCheck.Checked $KeepStylesCheck.Checked $SeparateCheck.Checked $LogCheck.Checked $LogText.Text
         $CommandText.Text = $CommandLine
      } # $handler_LogCheck_CheckStateChanged

      $handler_RWEXportForm_Shown={
         $SortMethod = $SortComboBox.SelectedIndex + 1
         $CommandLine = BuildCommandLine $ScriptText.Text $SourceText.Text $DestinationText.Text $SortMethod $SimpleImgText.Text $SmartImgText.Text $CSSText.Text $PrefixCheck.Checked $SuffixCheck.Checked $DetailsCheck.checked $IndentCheck.Checked $InlineStatsCheck.Checked $KeepStylesCheck.Checked $SeparateCheck.Checked $LogCheck.Checked $LogText.Text
         $CommandText.Text = $CommandLine
      }

      $handler_RunButton_Click={
         $RWExportForm.Enabled = $false
         Invoke-Expression $CommandText.Text
         $RWExportForm.Enabled = $true
      } # $handler_RunButton_Click

      $handler_SaveButton_Click={
         $SaveFileDialog = New-Object System.Windows.Forms.SaveFileDialog
         $SaveFileDialog.initialDirectory = ".\"
         $SaveFileDialog.filter = “PowerShell Files (*.ps1)| *.ps1”
         # $OpenFileDialog.showhelp = $true
         [void]$SaveFileDialog.ShowDialog()
         $CommandText.Text | Out-File $SaveFileDialog.filename
      } # $handler_SaveButton_Click

      $handler_LoadButton_Click={
      } # $handler_LoadButton_Click

      $OnLoadForm_StateCorrection={
         #Correct the initial state of the form to prevent the .Net maximized form issue
         $RWExportForm.WindowState = $InitialFormWindowState
      } # $OnLoadForm_StateCorrection

   #———————————————-
   #region Generated Form Code
   $RWExportForm.Text = “RWExport-To-HTML”
   $RWExportForm.Name = “RWExport-To-HTML”
   $RWExportForm.DataBindings.DefaultDataSourceUpdateMode = 0
   $System_Drawing_Size = New-Object System.Drawing.Size
   $System_Drawing_Size.Width = 650
   $System_Drawing_Size.Height = 450
   $RWExportForm.ClientSize = $System_Drawing_Size
   $RWExportForm.Add_Shown($handler_RWEXportForm_Shown)

   $x = 15
   $y = 15
   $xpadding = 10
   $ypadding = 5
   $Tab = 0

   $ScriptButton.TabIndex = $Tab
   $relativex = $x
   $relativey = $y
   $ScriptButton.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $ScriptButton.Name = “ScriptButton”
   $Width = 100
   $Height = 25
   $ScriptButton.Size = New-Object System.Drawing.Size($Width,$Height)
   $ScriptButton.Text = “Script File”
   $ScriptButton.add_Click($handler_ScriptButton_Click)

   $Tab = $Tab + 1
   $ScriptText.TabIndex = $Tab 
   $relativex = $relativex + $Width + $xpadding
   $relativey = $relativey
   $ScriptText.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $ScriptText.Name = “ScriptText”
   $Width = 510
   $Height = 25
   $ScriptText.Size = New-Object System.Drawing.Size($Width,$Height)
   $ScriptText.Text = “.\RWExport-To-HTML.ps1”
   $ScriptText.add_LostFocus($handler_TextBox_LostFocus)

   $Tab = $Tab + 1
   $SourceButton.TabIndex = $Tab
   $relativex = $x
   $relativey = $relativey + $height + $ypadding
   $SourceButton.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $SourceButton.Name = “SourceButton”
   $Width = 100
   $Height = 25
   $SourceButton.Size = New-Object System.Drawing.Size($Width,$Height)
   $SourceButton.Text = “Source File”
   $SourceButton.add_Click($handler_SourceButton_Click)

   $Tab = $Tab + 1
   $SourceText.TabIndex = $Tab
   $relativex = $relativex + $Width + $xpadding
   $relativey = $relativey
   $SourceText.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $SourceText.Name = “SourceText”
   $Width = 510
   $Height = 25
   $SourceText.Size = New-Object System.Drawing.Size($Width,$Height)
   $SourceText.Text = “.\MyRealm.rwoutput”
   $SourceText.add_LostFocus($handler_TextBox_LostFocus)

   $Tab = $Tab + 1
   $DestinationButton.TabIndex = $Tab
   $relativex = $x
   $relativey = $relativey + $height + $ypadding
   $DestinationButton.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $DestinationButton.Name = “DestinationButton”
   $Width = 100
   $Height = 25
   $DestinationButton.Size = New-Object System.Drawing.Size($Width,$Height)
   $DestinationButton.Text = “Destination File”
   $DestinationButton.add_Click($handler_DestinationButton_Click)

   $Tab = $Tab + 1
   $DestinationText.TabIndex = $Tab
   $relativex = $relativex + $Width + $xpadding
   $relativey = $relativey
   $DestinationText.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $DestinationText.Name = “DestinationText”
   $Width = 510
   $Height = 25
   $DestinationText.Size = New-Object System.Drawing.Size($Width,$Height)
   $DestinationText.Text = “.\MyRealm.html”
   $DestinationText.add_LostFocus($handler_TextBox_LostFocus)

   $Tab = $Tab + 1
   $CSSButton.TabIndex = $Tab
   $relativex = $x
   $relativey = $relativey + $height + $ypadding
   $CSSButton.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $CSSButton.Name = “CSSButton”
   $Width = 100
   $Height = 25
   $CSSButton.Size = New-Object System.Drawing.Size($Width,$Height)
   $CSSButton.Text = “CSS File”
   $CSSButton.add_Click($handler_CSSButton_Click)

   $Tab = $Tab + 1
   $CSSText.TabIndex = $Tab
   $relativex = $relativex + $Width + $xpadding
   $relativey = $relativey
   $CSSText.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $CSSText.Name = “CSSText”
   $Width = 510
   $Height = 25
   $CSSText.Size = New-Object System.Drawing.Size($Width,$Height)
   $CSSText.Text = “main.css”
   $CSSText.add_LostFocus($handler_TextBox_LostFocus)

   $Tab = $Tab + 1
   $LogCheck.TabIndex = $Tab
   $relativex = $x
   $relativey = $relativey + $height + $ypadding
   $LogCheck.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $LogCheck.Name = “LogCheck”
   $Width = 15
   $Height = 25
   $LogCheck.Size = New-Object System.Drawing.Size($Width,$Height)
   $LogCheck.Checked = $false
   $LogCheck.Add_CheckStateChanged($handler_LogCheck_CheckStateChanged)

   $Tab = $Tab + 1
   $LogButton.TabIndex = $Tab
   $relativex = $relativex + $Width + $xpadding
   $relativey = $relativey
   $LogButton.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $LogButton.Name = “LogButton”
   $Width = 75
   $Height = 25
   $LogButton.Size = New-Object System.Drawing.Size($Width,$Height)
   $LogButton.Text = “Log File”
   $LogButton.add_Click($handler_LogButton_Click)
   $LogButton.Enabled = $false

   $Tab = $Tab + 1
   $LogText.TabIndex = $Tab
   $relativex = $relativex + $Width + $xpadding
   $relativey = $relativey
   $LogText.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $LogText.Name = “LogText”
   $Width = 510
   $Height = 25
   $LogText.Size = New-Object System.Drawing.Size($Width,$Height)
   $LogText.Text = “.\RWExport.log”
   $LogText.add_LostFocus($handler_TextBox_LostFocus)
   $LogText.Enabled = $false

   $Tab = $Tab + 1
   $SortLabel.TabIndex = $Tab
   $relativex = $x + 20
   $relativey = $relativey + $Height + $ypadding
   $yoffset = $relativey + 5
   $SortLabel.Location = New-Object System.Drawing.Size($relativex,$yoffset)
   $SortLabel.Name = “SortLabel”
   $Width = 80
   $Height = 25
   $SortLabel.Size = New-Object System.Drawing.Size($Width,$Height)
   $SortLabel.Text = “Sort Topics By”

   $Tab = $Tab + 1
   $SortComboBox.TabIndex = $Tab
   $relativex = $relativex + $Width + $xpadding
   $relativey = $relativey
   $SortComboBox.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $SortComboBox.Name = “SortComboBox”
   $Width = 150
   $Height = 15
   $SortComboBox.Size = New-Object System.Drawing.Size($Width,$Height)
   $SortComboBox.DropDownStyle = [System.Windows.Forms.ComboBoxStyle]::DropDownList
   [void] $SortComboBox.Items.Add("1: Name")
   [void] $SortComboBox.Items.Add("2: Prefix, Name")
   [void] $SortComboBox.Items.Add("3: Category, Name")
   [void] $SortComboBox.Items.Add("4: Category,Prefix,Name")
   $SortComboBox.SelectedIndex = 1
   $SortComboBox.add_SelectedIndexChanged($SortComboBox_SelectedIndexChanged)

   $Tab = $Tab + 1
   $SimpleImgLabel.TabIndex = $Tab
   $relativex = $relativex + $width + $xpadding + 10
   $relativey = $relativey
   $yoffset = $relativey + 5
   $SimpleImgLabel.Location = New-Object System.Drawing.Size($relativex,$yoffset)
   $SimpleImgLabel.Name = “SimpleImgLabel”
   $Width = 105
   $Height = 15
   $SimpleImgLabel.Size = New-Object System.Drawing.Size($Width,$Height)
   $SimpleImgLabel.Text = “Scale Pictures by %”

   $Tab = $Tab + 1
   $SimpleImgText.TabIndex = $Tab
   $relativex = $relativex + $Width + $xpadding
   $relativey = $relativey
   $SimpleImgText.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $SimpleImgText.Name = “SimpleImgText”
   $Width = 30
   $Height = 15
   $SimpleImgText.Size = New-Object System.Drawing.Size($Width,$Height)
   $SimpleImgText.Text = “0”
   $SimpleImgText.add_LostFocus($handler_TextBox_LostFocus)

   $Tab = $Tab + 1
   $SmartImgLabel.TabIndex = $Tab
   $relativex = $relativex + $width + $xpadding + 10
   $relativey = $relativey
   $yoffset = $relativey + 5
   $SmartImgLabel.Location = New-Object System.Drawing.Size($relativex,$yoffset)
   $SmartImgLabel.Name = “SmartImgLabel”
   $Width = 135
   $Height = 15
   $SmartImgLabel.Size = New-Object System.Drawing.Size($Width,$Height)
   $SmartImgLabel.Text = “Scale Smart Images by %”

   $Tab = $Tab + 1
   $SmartImgText.TabIndex = $Tab
   $relativex = $relativex + $Width + $xpadding
   $relativey = $relativey
   $SmartImgText.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $SmartImgText.Name = “SmartImgText”
   $Width = 30
   $Height = 15
   $SmartImgText.Size = New-Object System.Drawing.Size($Width,$Height)
   $SmartImgText.Text = “0”
   $SmartImgText.add_LostFocus($handler_TextBox_LostFocus)

   $x1 = $x + 25
   $x2 = $x1 + 175
   $x3 = $x2 + 175
   $y2padding = 20

   $Tab = $Tab + 1
   $PrefixCheck.TabIndex = $Tab
   $relativex = $x1
   $relativey = $relativey + $Height + $y2padding
   $PrefixCheck.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $LogCheck.Name = “PrefixCheck”
   $Width = 15
   $Height = 15
   $PrefixCheck.Size = New-Object System.Drawing.Size($Width,$Height)
   $PrefixCheck.Checked = $true
   $PrefixCheck.Add_CheckStateChanged($handler_CheckBox_CheckStateChanged)

   $Tab = $Tab + 1
   $PrefixLabel.TabIndex = $Tab
   $relativex = $relativex + $Width + $xpadding
   $relativey = $relativey
   $yoffset = $relativey + 5
   $PrefixLabel.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $PrefixLabel.Name = “PrefixLabel”
   $Width = 125
   $Height = 15
   $PrefixLabel.Size = New-Object System.Drawing.Size($Width,$Height)
   $PrefixLabel.Text = “Include Topic Prefixes”

   $Tab = $Tab + 1
   $SuffixCheck.TabIndex = $Tab
   $relativex = $x2 # $relativex + $Width + $xpadding
   $relativey = $relativey
   $SuffixCheck.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $SuffixCheck.Name = “SuffixCheck”
   $Width = 15
   $Height = 15
   $SuffixCheck.Size = New-Object System.Drawing.Size($Width,$Height)
   $SuffixCheck.Checked = $true
   $SuffixCheck.Add_CheckStateChanged($handler_CheckBox_CheckStateChanged)

   $Tab = $Tab + 1
   $SuffixLabel.TabIndex = $Tab
   $relativex = $relativex + $Width + $xpadding
   $relativey = $relativey
   $yoffset = $relativey + 5
   $SuffixLabel.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $SuffixLabel.Name = “SuffixLabel”
   $Width = 120
   $Height = 15
   $SuffixLabel.Size = New-Object System.Drawing.Size($Width,$Height)
   $SuffixLabel.Text = “Include Topic Suffixes”

   $Tab = $Tab + 1
   $DetailsCheck.TabIndex = $Tab
   $relativex = $x3 # $relativex + $Width + $xpadding
   $relativey = $relativey
   $DetailsCheck.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $DetailsCheck.Name = “DetailsCheck”
   $Width = 15
   $Height = 15
   $DetailsCheck.Size = New-Object System.Drawing.Size($Width,$Height)
   $DetailsCheck.Checked = $true
   $DetailsCheck.Add_CheckStateChanged($handler_CheckBox_CheckStateChanged)

   $Tab = $Tab + 1
   $DetailsLabel.TabIndex = $Tab
   $relativex = $relativex + $Width + $xpadding
   $relativey = $relativey
   $yoffset = $relativey + 5
   $DetailsLabel.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $DetailsLabel.Name = “DetailsLabel”
   $Width = 120
   $Height = 15
   $DetailsLabel.Size = New-Object System.Drawing.Size($Width,$Height)
   $DetailsLabel.Text = “Include Topic Details”

   $Tab = $Tab + 1
   $IndentCheck.TabIndex = $Tab
   $relativex = $x1 # $relativex + $Width + $xpadding
   $relativey = $relativey + $height
   $IndentCheck.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $IndentCheck.Name = “IndentCheck”
   $Width = 15
   $Height = 15
   $IndentCheck.Size = New-Object System.Drawing.Size($Width,$Height)
   $IndentCheck.Checked = $true
   $IndentCheck.Add_CheckStateChanged($handler_CheckBox_CheckStateChanged)

   $Tab = $Tab + 1
   $IndentLabel.TabIndex = $Tab
   $relativex = $relativex + $Width + $xpadding
   $relativey = $relativey
   $yoffset = $relativey + 5
   $IndentLabel.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $IndentLabel.Name = “IndentLabel”
   $Width = 250
   $Height = 15
   $IndentLabel.Size = New-Object System.Drawing.Size($Width,$Height)
   $IndentLabel.Text = “Indent Contained Topics and Subsections”

   $Tab = $Tab + 1
   $InlineStatsCheck.TabIndex = $Tab
   $relativex = $x3 # $relativex + $Width + $xpadding
   $relativey = $relativey # + $height + $y2padding
   $InlineStatsCheck.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $InlineStatsCheck.Name = “InlineStatsCheck”
   $Width = 15
   $Height = 15
   $InlineStatsCheck.Size = New-Object System.Drawing.Size($Width,$Height)
   $InlineStatsCheck.Add_CheckStateChanged($handler_CheckBox_CheckStateChanged)

   $Tab = $Tab + 1
   $InlineStatsLabel.TabIndex = $Tab
   $relativex = $relativex + $Width + $xpadding
   $relativey = $relativey
   $yoffset = $relativey + 5
   $InlineStatsLabel.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $InlineStatsLabel.Name = “InlineStatsLabel”
   $Width = 250
   $Height = 15
   $InlineStatsLabel.Size = New-Object System.Drawing.Size($Width,$Height)
   $InlineStatsLabel.Text = “Display Full Stat Blocks Inline”

   $Tab = $Tab + 1
   $KeepStylesCheck.TabIndex = $Tab
   $relativex = $x1 # $relativex + $Width + $xpadding
   $relativey = $relativey + $height # + $height + $y2padding
   $KeepStylesCheck.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $KeepStylesCheck.Name = “KeepStylesCheck”
   $Width = 15
   $Height = 15
   $KeepStylesCheck.Size = New-Object System.Drawing.Size($Width,$Height)
   $KeepStylesCheck.Add_CheckStateChanged($handler_CheckBox_CheckStateChanged)

   $Tab = $Tab + 1
   $KeepStylesLabel.TabIndex = $Tab
   $relativex = $relativex + $Width + $xpadding
   $relativey = $relativey
   $yoffset = $relativey + 5
   $KeepStylesLabel.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $KeepStylesLabel.Name = “KeepStylesLabel”
   $Width = 250
   $Height = 15
   $KeepStylesLabel.Size = New-Object System.Drawing.Size($Width,$Height)
   $KeepStylesLabel.Text = “Preserve  Original Text Formatting”

   $Tab = $Tab + 1
   $SeparateCheck.TabIndex = $Tab
   $relativex = $x3 # $relativex + $Width + $xpadding
   $relativey = $relativey
   $SeparateCheck.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $SeparateCheck.Name = “SeparateCheck”
   $Width = 15
   $Height = 15
   $SeparateCheck.Size = New-Object System.Drawing.Size($Width,$Height)
   $SeparateCheck.Checked = $true
   $SeparateCheck.Add_CheckStateChanged($handler_CheckBox_CheckStateChanged)

   $Tab = $Tab + 1
   $SeparateLabel.TabIndex = $Tab
   $relativex = $relativex + $Width + $xpadding
   $relativey = $relativey
   $yoffset = $relativey + 5
   $SeparateLabel.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $SeparateLabel.Name = “SeparateLabel”
   $Width = 250
   $Height = 15
   $SeparateLabel.Size = New-Object System.Drawing.Size($Width,$Height)
   $SeparateLabel.Text = “Insert a Divider Line Between Snippets”
   
   $Tab = $Tab + 1
   $CommandLabel.TabIndex = $Tab
   $relativex = $x
   $relativey = $relativey + $height + $ypadding
   $CommandLabel.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $CommandLabel.Name = “CommandLabel”
   $Width = 100
   $Height = 15
   $CommandLabel.Size = New-Object System.Drawing.Size($Width,$Height)
   $CommandLabel.Text = “CommandLine”
   $CommandLabel.add_Click($handler_ScriptButton_Click)

   $Tab = $Tab + 1
   $CommandText.TabIndex = $Tab 
   $relativex = $x
   $relativey = $relativey + $Height
   $CommandText.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $CommandText.Name = “CommandText”
   $Width = 620
   $Height = 100
   $CommandText.Size = New-Object System.Drawing.Size($Width,$Height)
   $CommandText.Multiline = $true
   $CommandText.ReadOnly = $true
   $CommandText.Text = “.\RWExport-To-HTML.ps1”

   $RunButton.TabIndex = $Tab
   $relativex = 215
   $relativey = $relativey + $Height + 10
   $RunButton.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $RunButton.Name = “RunButton”
   $Width = 210
   $Height = 25
   $RunButton.Size = New-Object System.Drawing.Size($Width,$Height)
   $RunButton.Text = “Run Script”
   $RunButton.add_Click($handler_RunButton_Click)

   $SaveButton.TabIndex = $Tab
   $relativex = 215
   $relativey = $relativey + $Height + $ypadding
   $SaveButton.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $SaveButton.Name = “SaveButton”
   $Width = 100
   $Height = 25
   $SaveButton.Size = New-Object System.Drawing.Size($Width,$Height)
   $SaveButton.Text = “Save Script”
   $SaveButton.add_Click($handler_SaveButton_Click)

   $LoadButton.TabIndex = $Tab
   $relativex = $relativex + $width + $xpadding
   $relativey = $relativey
   $LoadButton.Location = New-Object System.Drawing.Size($relativex,$relativey)
   $LoadButton.Name = “LoadButton”
   $Width = 300
   $Height = 25
   $LoadButton.Size = New-Object System.Drawing.Size($Width,$Height)
   $LoadButton.Text = “Load Script (I don't do anything yet. Don't judge me.)”
   $LoadButton.add_Click($handler_LoadButton_Click)

   $RWExportForm.Controls.Add($ScriptButton)
   $RWExportForm.Controls.Add($ScriptText)
   $RWExportForm.Controls.Add($SourceButton)
   $RWExportForm.Controls.Add($SourceText)
   $RWExportForm.Controls.Add($DestinationButton)
   $RWExportForm.Controls.Add($DestinationText)
   $RWExportForm.Controls.Add($CSSButton)
   $RWExportForm.Controls.Add($CSSText)
   $RWExportForm.Controls.Add($LogCheck)
   $RWExportForm.Controls.Add($LogButton)
   $RWExportForm.Controls.Add($LogText)
   $RWExportForm.Controls.Add($SortLabel)
   $RWExportForm.Controls.Add($SortComboBox)
   $RWExportForm.Controls.Add($SimpleImgLabel)
   $RWExportForm.Controls.Add($SimpleImgText)
   $RWExportForm.Controls.Add($SmartImgLabel)
   $RWExportForm.Controls.Add($SmartImgText)
   $RWExportForm.Controls.Add($PrefixCheck)
   $RWExportForm.Controls.Add($PrefixLabel)
   $RWExportForm.Controls.Add($SuffixCheck)
   $RWExportForm.Controls.Add($SuffixLabel)
   $RWExportForm.Controls.Add($DetailsCheck)
   $RWExportForm.Controls.Add($DetailsLabel)
   $RWExportForm.Controls.Add($IndentCheck)
   $RWExportForm.Controls.Add($IndentLabel)
   $RWExportForm.Controls.Add($InlineStatsCheck)
   $RWExportForm.Controls.Add($InlineStatsLabel)
   $RWExportForm.Controls.Add($KeepStylesCheck)
   $RWExportForm.Controls.Add($KeepStylesLabel)
   $RWExportForm.Controls.Add($SeparateCheck)
   $RWExportForm.Controls.Add($SeparateLabel)
   $RWExportForm.Controls.Add($CommandLabel)
   $RWExportForm.Controls.Add($CommandText)

   $RWExportForm.Controls.Add($RunButton)
   $RWExportForm.Controls.Add($SaveButton)
   $RWExportForm.Controls.Add($LoadButton)
   # endregion Generated Form Code

   # Save the initial state of the form
   $InitialFormWindowState = $RWExportForm.WindowState
   #Init the OnLoad event to correct the initial state of the form
   $RWExportForm.add_Load($OnLoadForm_StateCorrection)

   #Show the Form
   $RWExportForm.ShowDialog()| Out-Null
} #End Function

#Call the Function
GenerateForm 